obstacle_range: 2.5
raytrace_range: 3.0
footprint: [ [0.3, 0.29], [-0.3, 0.29], [-0.3, -0.29], [0.3, -0.29] ]
# robot_radius: 0.4

cost_scaling_factor: 0.1

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo_link, data_type: LaserScan, topic: /laser/scan, marking: true, clearing: true}

# point_cloud_sensor: {sensor_frame: hokuyo_link, data_type: PointCloud, topic: /laser/scan, marking: true, clearing: true}
